[package]
name = "prime-ribs"
version = "0.1.0"
authors = ["0xSilene <51803887+0xSilene@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.0"
ramp = "0.5.3"